### ISSUE TITLE
Suggestion for parameters

### ISSUE THREAD

**Issue by MikhaelManurung** [KrishnaswamyLab/Multiscale_PHATE#3]
Dear authors,

I have tried using this package on CyTOF data of ~ 3 million cells but it took such a long time. Do you have any recommendation or rule of thumbs for the parameters? 

Thanks in advance.

Mikhael

**Comment by mkuchroo** [comment]
Hi Mikhael,

Good to hear you are using our algorithm!

I would recommend you do the following things:
1. Make sure the MSP package you are using is most up to date (we recently
pushed a newer and faster implementation to git)
2. MSP becomes increasingly fast when you add additional parallel threads.
Typically, I run it with 10 threads (n_jobs=10). If your system can handle
this I would recommend.
3. How many features are you working with? We tested our algorithm most
extensively on flow data which has 16 features. Having many more features
would slow down the initial coarse graining step somewhat (though not
substantially). This would mean that you probably wouldn't be able to embed
3 million cells in 7 minutes (which is what I am able to achieve with 10
threads on flow data) but hopefully not too much longer than that
(depending on number of features obviously).

Please let me know if this is helpful and if you have any other questions!

Manik

**Comment by MikhaelManurung** [comment]
Hi Manik,

Thank you for the suggestion! Setting n_jobs did the trick. I thought it was set to `-1` by default.

Could you share some example on showing and picking the resolution of the clusters as well as an integrated workflow with MELD? 

Thanks in advance. I am closing this issue.
