### ISSUE TITLE
Meaning of Multiscale PHATE levels

### ISSUE THREAD

**Issue by wilsonjr** [KrishnaswamyLab/Multiscale_PHATE#4]
Hi, I am wondering if the levels of Multiscale PHATE correspond to actual data points.

For example, can I visualize an arbitrary level colored based on a pre-defined label or the levels correspond to the condensation of various datapoints (possibly with mixed labels)?

Thank you!

**Comment by mkuchroo** [comment]
Hi! So yes points visualized at a Multiscale PHATE level do correspond with underlying data points. In fact, you can find the direct link between them by running mp_op.NxT[visualization_level]. This will return a vector of mapping identities saying which of your input points map to which of your visualized points at the visualization level.

The next code update will include a means of mapping continuous values at the cell level to data points at the visualization level. Categorical labels are still a bit of a problem. Our solution is to compute the proportion of cells from each label that comprise a multiscale point. This will also be released in the next code update!

**Comment by wilsonjr** [comment]
Thank you!
I am closing this issue since my questions were answered.

**Comment by wilsonjr** [comment]
Hi, I was digging the code and found a solution:

level_indices = np.unique(mp_op.NxTs[levels[level]])
y_level = y[level_indices]
